Fix broken context extraction for large files.
CopilotC-Nvim/CopilotChat.nvim pull request #168
Opened 2024-03-14 21:04 UTC by dmadisetti

Bug on line 83.

As was, it always returned bool, nil, which would push into the next conditional, which could fall through if the file type is not directly recognized.

In these cases, it's also returning nil. Calling functions treat the response as a table, which leads to unexpected failures.

2024-03-14 23:35 UTC, deathbeam requested changes

2024-03-14 23:35 UTC, deathbeam commented on lua/CopilotChat/context.lua
> +      outline = M.build_outline(bufnr)
this is incorrect, outline is list of outlines, it do not returns list by itself.

2024-03-14 23:35 UTC, deathbeam commented on lua/CopilotChat/context.lua
> +    return {}
why? Just handle nil outside, do not return empty tables

2024-03-14 23:35 UTC, deathbeam commented on lua/CopilotChat/context.lua
> +      return {}
same here

2024-03-14 23:35 UTC, deathbeam commented on lua/CopilotChat/context.lua
> +  local ok, parser = pcall(vim.treesitter.get_parser, bufnr, lang)
if lang is nil vim.treesitter.get_parser should not be called. if the and/or wasnt working, then just add normal if else around i guess

2024-03-14 23:52 UTC, dmadisetti commented on lua/CopilotChat/context.lua
> +  local ok, parser = pcall(vim.treesitter.get_parser, bufnr, lang)
from testing, if lang is nil, it's inferred from the buffer. It's non-breaking

but alright

2024-03-14 23:58 UTC, dmadisetti commented
Actually tested this time!

2024-03-15 00:22 UTC, deathbeam commented on lua/CopilotChat/context.lua
> +  if not lang then
I did not meant early return but simply to not call the vim.treesitter.get_parser when lang is nil and go straight to fallback. Thats what the original code did (or tried to) e.g avoided the unnecessary call and went to check get_parsr for ft

2024-03-15 00:26 UTC, deathbeam commented on lua/CopilotChat/context.lua
> +      outline = M.build_outline(bufnr)
this is still incorrect, embed expects list of outlines as input, now you are sending just single outline. If you want to skip nil result, just check it here do not overwrite the list

2024-03-15 00:32 UTC, dmadisetti commented on lua/CopilotChat/context.lua
> +      outline = M.build_outline(bufnr)
That's why my original PR sent back an empty list- with your recommendation you have a mixed type signature

2024-03-15 00:40 UTC, deathbeam commented on lua/CopilotChat/context.lua
> +      outline = M.build_outline(bufnr)
But you cant sometimes send back empty list and sometimes send back just the outline which isnt a list, thats why the original solution did not worked

2024-03-15 00:42 UTC, deathbeam commented on lua/CopilotChat/context.lua
> +      outline = M.build_outline(bufnr)
E.g look at what is build_outline actually returning when it succeeds, I think that is where most of the confusion lies

2024-03-15 00:54 UTC, dmadisetti commented on lua/CopilotChat/context.lua
> +      outline = M.build_outline(bufnr)
You're right; optionals seem common in Lua. Added a filter to address `nils`

2024-03-15 01:13 UTC, deathbeam commented on lua/CopilotChat/context.lua
> +  ok, parser = false, nil
This should be local

2024-03-15 02:00 UTC, deathbeam approved these changes

2024-03-15 04:18 UTC, merged

2024-03-15 04:18 UTC, jellydn commented
@all-contributors add @dmadisetti for code.