Feat: add configurable option to disable "done!" notification
CopilotC-Nvim/CopilotChat.nvim pull request #241
Opened 2024-03-26 04:10 UTC by D7ry

By configuring `notify_done` variable in opts, users can disable the "done!" notification that some may find a bit distracting.

2024-03-26 10:29 UTC, deathbeam commented
I think way better way would be to remove the notify completely from where its being called now and just set default callback (thats currently by default nil) to be function that calls `vim.notify`.

2024-03-26 15:24 UTC, deathbeam requested changes
As i said in my response, should just be callback imo

2024-03-27 05:55 UTC, D7ry commented
> As i said in my response, should just be callback imo

I believe just not setting the default callback is better; removed the notify completely!

2024-03-27 06:15 UTC, deathbeam commented
Yea i agree, much cleaner solution

2024-03-27 06:15 UTC, deathbeam approved these changes

2024-03-27 06:16 UTC, deathbeam commented on lua/CopilotChat/config.lua
> +
Same here

2024-03-27 06:16 UTC, deathbeam commented on README.md
> +
Extra new line, remove

2024-03-27 06:16 UTC, deathbeam commented on lua/CopilotChat/chat.lua
> +local Chat = class(function(self, mark_ns, help, on_buf_create, config)
Im not sure why are you passing config here

2024-03-27 06:23 UTC, D7ry commented on lua/CopilotChat/chat.lua
> +local Chat = class(function(self, mark_ns, help, on_buf_create, config)
updated. the config was required previous for getting the option but no longer

2024-03-27 09:12 UTC, deathbeam requested changes
see comments

2024-03-27 09:22 UTC, jellydn commented on README.md
> +
```suggestion
```

2024-03-27 09:22 UTC, jellydn commented on lua/CopilotChat/config.lua
> +
```suggestion
```

2024-03-27 09:30 UTC, merged

2024-03-27 09:31 UTC, jellydn commented
@all-contributors add @D7ry for code.