fix: consider 0.10 as stable and 0.11 as nightly
CopilotC-Nvim/CopilotChat.nvim pull request #322
Opened 2024-05-17 04:50 UTC by frolvanya

closes #321 

Let's consider 0.10 as stable version from now on. I suppose 0.9.5 still can be considered as stable for a few months until majority of people will migrate to 0.10

2024-05-17 08:39 UTC, deathbeam requested changes

2024-05-17 08:39 UTC, deathbeam commented on lua/CopilotChat/health.lua
> +  local is_good_stable = vim.fn.has('nvim-0.9.5') == 1 or vim.fn.has('nvim-0.10') == 1
is this necessary? 0.10 will already have 0.9.5 no?

2024-05-17 08:39 UTC, deathbeam commented on lua/CopilotChat/health.lua
> +  local is_nightly = vim.fn.has('nvim-0.11') == 1
Thinking about this, maybe is_nightly check should be simply vim_version:match('dev%-(%d+)'). If its not nil then at the dev_number = just do tonumber(is_nightly) etc so we dont have to change the current nightly version all the time

2024-05-17 12:40 UTC, frolvanya commented on lua/CopilotChat/health.lua
> +  local is_nightly = vim.fn.has('nvim-0.11') == 1
Done
https://github.com/CopilotC-Nvim/CopilotChat.nvim/blob/becc76f54cab703e031a6978f8fd639280ae6db0/lua/CopilotChat/health.lua#L44-L61

2024-05-17 12:41 UTC, frolvanya commented on lua/CopilotChat/health.lua
> +  local is_good_stable = vim.fn.has('nvim-0.9.5') == 1 or vim.fn.has('nvim-0.10') == 1
It will not find dev tag in 0.10 version as it's stable now and it won't consider it as stable, therefore we need to check if the version is either 0.9.5 or 0.10.0

2024-05-17 14:15 UTC, deathbeam commented on lua/CopilotChat/health.lua
> +  local dev_number = tonumber(vim_version:match('dev%-(%d+)'))
dont call tonumber here as it can be nil, just do the mathc without tonumber  then in the if check >= 2500 do the tonumber

2024-05-17 14:27 UTC, frolvanya commented on lua/CopilotChat/health.lua
> +  local dev_number = tonumber(vim_version:match('dev%-(%d+)'))
`tonumber` return optional number, so it's safe to do it. Basically tonumber(nil) == nil, so `if dev_number` will check if dev_number exists and it's possible to parse it as int

<img width="238" alt="image" src="https://github.com/CopilotC-Nvim/CopilotChat.nvim/assets/59515280/94a9b9ce-d910-467f-b42a-6313bef25ae0">
<img width="223" alt="image" src="https://github.com/CopilotC-Nvim/CopilotChat.nvim/assets/59515280/43dd8adc-aabc-47db-ae80-27b2e77308f3">

2024-05-17 14:29 UTC, frolvanya commented on lua/CopilotChat/health.lua
> +  local dev_number = tonumber(vim_version:match('dev%-(%d+)'))
But if you want, I can to this. IMO, it just increases code length

```lua
local dev_version_str = vim_version:match('dev%-(%d+)')

if dev_version_str then
  local dev_number = tonumber(dev_version_str)
  if dev_number and dev_number >= 2500 then
    ok('nvim: ' .. vim_version)
  else
    error(
      'nvim: outdated, please upgrade to an up-to-date nightly version. See "https://github.com/neovim/neovim".'
    )
  end
elseif is_good_stable then
  ok('nvim: ' .. vim_version)
else
  error('nvim: unsupported, please upgrade to 0.9.5 or later. See "https://neovim.io/".')
end
```

2024-05-17 15:00 UTC, deathbeam commented on lua/CopilotChat/health.lua
> +  local dev_number = tonumber(vim_version:match('dev%-(%d+)'))
Ah alright, I thought tonumber will fail on nil. Looks good then

2024-05-17 15:01 UTC, merged

2024-05-24 16:00 UTC, WillEhrendreich commented
I'm on a nightly of 0.11.0 but checkhealth fails and says I should upgrade. 
![image](https://github.com/CopilotC-Nvim/CopilotChat.nvim/assets/55286472/b6e8ee35-2b83-46f1-8980-b7375f251882)

2024-05-24 16:24 UTC, deathbeam commented
Oh the commit number is since last release, need to fix that

2024-05-24 16:39 UTC, frolvanya commented
> Oh the commit number is since last release, need to fix that

Oops, I messed up. Do you want me to fix it? If so, do you want to completely remove this section with `>= 2500` or replace it with `>= 67` (since neovim-0.11 has dev number 67)