feat: enhanced header rendering in the chat window
CopilotC-Nvim/CopilotChat.nvim pull request #336
Opened 2024-05-27 18:04 UTC by folke

As discussed, the separator is now repeated in a virtual line and has hl group `CopilotChatSeparator`.

The headers have `hl_group` `CopilotChatHeader`.

I didn't change the default header strings, so they still have `##`, but that's no longer needed to get the same styling.
 
![image](https://github.com/CopilotC-Nvim/CopilotChat.nvim/assets/292349/a180cf4d-1739-4c47-b196-56cce581dc4e)

With custom header strings:

![image](https://github.com/CopilotC-Nvim/CopilotChat.nvim/assets/292349/9ea1e3b3-2725-435f-bbfc-f9a958db74ba)

Closes #334

2024-05-27 18:05 UTC, folke commented on lua/CopilotChat/chat.lua
> +  self.header_ns = vim.api.nvim_create_namespace('copilot-chat-headers')
Creating a namespace returns the existing one when it already exists, so no need to create it during setup and then pass it down.

2024-05-27 18:28 UTC, deathbeam requested changes

2024-05-27 18:28 UTC, deathbeam commented on lua/CopilotChat/chat.lua
> +  local lines = vim.api.nvim_buf_get_lines(self.bufnr, 0, -1, false)
Hmm would it be better to add the extmark when the headers are being appended to the chat instead of rereading the whole buffer every time? If i understand extmarks correctly they should persist just fine so readding them after every text change should not be necessary

2024-05-27 18:32 UTC, folke commented on lua/CopilotChat/chat.lua
> +  local lines = vim.api.nvim_buf_get_lines(self.bufnr, 0, -1, false)
I'd keep it like this, since this is a really fast operation and will ensure the extmarks are always correct.

Plugins like lazy.nvim, trouble.nvim and other I didnt write, all basically re-render the whole buffer whenever something in their data changes. For trouble and lazy this means a lot of extmarks. The extmarks for copilot chat are nothing compared to that :)

2024-05-27 18:34 UTC, folke commented on lua/CopilotChat/chat.lua
> +  local lines = vim.api.nvim_buf_get_lines(self.bufnr, 0, -1, false)
Same with treesitter. Simple changes in your source file, can mean lots of updates in terms of extmarks.

2024-05-27 18:48 UTC, deathbeam commented on lua/CopilotChat/chat.lua
> +  local lines = vim.api.nvim_buf_get_lines(self.bufnr, 0, -1, false)
Interesting, I assumed it can get pretty bad with a lot of lines and extmarks but if its quick then sounds good as this way its a lot simpler to manage.

2024-05-27 18:48 UTC, deathbeam approved these changes

2024-05-27 18:51 UTC, merged

2024-05-28 01:13 UTC, GitMurf commented
@deathbeam will this effect saving a chat conversation? Historically you could save the buffer as markdown file and have a nicely formatted conversation in markdown. Is that no longer the case if we are removing the ## Heading Syntax?

2024-05-28 05:03 UTC, deathbeam commented
> @deathbeam will this effect saving a chat conversation? Historically you could save the buffer as markdown file and have a nicely formatted conversation in markdown. Is that no longer the case if we are removing the ## Heading Syntax?

The syntax is still there this just added some extmarks on top for better visuals and thats it, do not affects how the data are stored at all

2024-05-28 05:16 UTC, GitMurf commented
> The syntax is still there this just added some extmarks on top for better visuals and thats it, do not affects how the data are stored at all

Oh ok. I guess I got a little confused with folke's custom header strings screenshot above.