Allow runtime selection of models with `:CopilotChatModels`
CopilotC-Nvim/CopilotChat.nvim pull request #368
Opened 2024-07-16 14:46 UTC by gptlang

CC @deathbeam & CC @jellydn 

I haven't touched Lua in a while and don't really know how the codebase works anymore. Could you guys check if I did anything wrong

2024-07-16 14:54 UTC, pidgeon777 commented
So, to clarify, it will be possible to dynamically choose which model to use for any given request?

2024-07-16 14:56 UTC, gptlang commented
Well, you'll have to specify it. It's not automagic like vscode. It's currently a bit slow due to fetching the models on each request. We might want to cache it per session.

2024-07-16 15:07 UTC, gptlang commented
But the point is to make discovery of available models easier, for example to check if gpt-4o is available to you

2024-07-16 23:35 UTC, jellydn commented
Hi, @gptlang What if we save the selected model and use that config for next time? It's similar to what `Copilot Auth` does. So we don't need to call models every time. What do you think?

2024-07-17 04:41 UTC, gptlang commented
I don't want to touch `init.lua` and would rather have that be followed by default. If you want to use a model by default, set it there

2024-07-17 12:18 UTC, jellydn approved these changes
LGTM!

2024-07-17 12:48 UTC, deathbeam requested changes

2024-07-17 12:48 UTC, deathbeam commented on lua/CopilotChat/init.lua
> +  state.copilot:select_model(function(model)
this should only change M.config, and the config itself shouldnt ever be nil, it shouldnt change stateconfig.model or default_config.model

2024-07-17 12:48 UTC, deathbeam commented on lua/CopilotChat/copilot.lua
> +  if self.models_cache ~= nil then
you can reduce the code duplication here by making inner local function that does the vim.ui.select. but also i think the select shouldnt be here at all, it should be in the select_model method in init.lua, this should simply call the callback with the model_cache

2024-07-17 15:27 UTC, merged